version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    container_name: psk-redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: mysql_test
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: psk-mysql

  nginx:
    image: nginx:latest
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ../web:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    container_name: psk-nginx

  app:
    build: ./psk-app
    volumes:
      - ../web:/var/www/html
    links:
      - mysql
    environment:
      DATABASE_HOST: "psk-mysql"
      DATABASE_NAME: ${DATABASE}
      DATABASE_USER: ${USER_NAME}
      DATABASE_PASSWORD: ${USER_PASSWORD}
    container_name: psk-app
